apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-storage
  template:
    metadata:
      labels:
        app: fastapi-storage
    spec:
      containers:
      - name: fastapi-storage
        image: docker.io/artempyzhov/fastapi_storage:1.0.8
        ports:
            - name: web
              containerPort: 8000
        env:
          - name: DATABASE_URL
            value: postgresql://postgres:1231@postgres-svc:5432/postgres
