"""names changing

Revision ID: 24423b1eae53
Revises: 859cc165443e
Create Date: 2023-10-28 10:27:56.207043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24423b1eae53'
down_revision: Union[str, None] = '859cc165443e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_column('document', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('document', 'owner_id')
    # ### end Alembic commands ###
