"""add docs 2

Revision ID: 859cc165443e
Revises: ee228c0cf1ef
Create Date: 2023-10-27 18:33:15.792420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859cc165443e'
down_revision: Union[str, None] = 'ee228c0cf1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('owner', sa.String(), nullable=False))
    op.add_column('document', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('document', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('document', 'name')
    op.drop_column('document', 'owner')
    # ### end Alembic commands ###
