"""referrals

Revision ID: af84093c3323
Revises: 9287210d93f2
Create Date: 2023-10-30 16:00:24.081670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af84093c3323'
down_revision: Union[str, None] = '9287210d93f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['document.id'], )
    )
    op.drop_table('referals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referals',
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['document.id'], name='referals_target_id_fkey')
    )
    op.drop_table('referrals')
    # ### end Alembic commands ###
